### ISSUE TITLE
Hello，我能试用你的启动器吗？

### ISSUE THREAD

**Issue by ExDragine** [to2mbn/LoliXL#1]
自从黄鱼卖了hmcl我就想试试你的loliXL，好吗/

**Comment by yushijinhun** [comment]
抱歉啊，我们的启动器目前仍在开发中。

目前我们这里的开发者有：
- @yushijinhun （负责架构）
- @Darkyoooooo （负责UI）
- @Mickeyxiami 

（前两者都是JMCCC的开发者）

@TT702、@ZhaiSoul帮忙设计UI并绘制效果图（他们都是BakaXL的开发者）。

启动器的UI部分使用JavaFX，使用OSGi进行模块化，使用JMCCC作为启动核心。
如果你有兴趣的话，也欢迎参与开发，可联系yushijinhun@gmail.com。

**Comment by ExDragine** [comment]
这样子阿，我不会玩Java，如果哪天内测能发我邮箱吗？
surfaceluck@outlook.com
谢谢你啦

**Comment by Cat7373** [comment]
感觉项目成熟之前其他人挺难插手的- -

**Comment by ExDragine** [comment]
确实，只能远观，我去HMCL那边继续搅和
PS 那活货就是死人

**Comment by 3TUSK** [comment]
@Edgeback 要说现在的话，为何不试试[MultiMC](http://multimc.org/)呢（https://github.com/MultiMC/MultiMC5 ）

**Comment by ExDragine** [comment]
英文，小学生会看不懂的~~~，虽然实用又好看
QUQ

**Comment by 3TUSK** [comment]
@Edgeback 有自带中文（简繁都有）的本地化啊。

**Comment by ExDragine** [comment]
@3TUSK  看到啦~~~

**Comment by ExDragine** [comment]
额。这UI制作效率也是。。。
而且磁贴化的化参考一下Redstone的UI设计比较好

**Comment by darkyzhou** [comment]
我们俩整天沉迷mc 没办法。。

**Comment by ghost** [comment]
希望各位可以早点开发出来，也希望可以本地化，

**Comment by darkyzhou** [comment]
最早8月上旬出0.1 本地化是完全支持的 而且启动器可以做到运行时实时更新语言

**Comment by yushijinhun** [comment]
要是搞不定。。。我就不搞了（专心JMCCC）

**Comment by darkyzhou** [comment]
搞不定 楼上女装 已经说好了

**Comment by yushijinhun** [comment]
窝日。。

**Comment by Cat7373** [comment]
女装 0.0
凑巧路过就看到了什么奇怪的东东 0.0

**Comment by Cat7373** [comment]
不如加个自动构建之类的东东，方便试用0.0

**Comment by yushijinhun** [comment]
主要是目前完成度太低。。没法看

**Comment by yushijinhun** [comment]
@Cat7373 我给LoliXL开了个[Jenkins](https://ci.to2mbn.org/job/LoliXL)

**Comment by ExDragine** [comment]
我去测试啦~
Bug会在这里反馈~
#Back敬上#
木有汇编好的吗。。

**Comment by Cat7373** [comment]
https://ci.to2mbn.org/job/LoliXL/3/org.to2mbn.lolixl$lolixl-package/

**Comment by ExDragine** [comment]
这白白的屏幕真心感人。。Windows 10 Redstone 64X     Java 8 update 101 64X
![image](https://cloud.githubusercontent.com/assets/17111186/17913866/e8870d66-69cf-11e6-84a0-3b1adabdb601.png)

**Comment by yushijinhun** [comment]
我要升初三了，所以可能进度会特别慢QAQ

**Comment by NekoCaffeine** [comment]
为什么没有把窝算进去啊你个混蛋，我感觉我会变成专门抓虫子的啊喂

**Comment by ExDragine** [comment]
听你们说话好感人~

**Comment by yushijinhun** [comment]
@Mickeyxiami 行行行我算进去了，不过pom.xml里我早就把你写到developers里去了

**Comment by ExDragine** [comment]
唔。。。几天没看，HMCL在开发者中的人气已经暴跌了。。。

**Comment by CatMe0w** [comment]
为何不试试用 Material Design 做UI呢？

**Comment by darkyzhou** [comment]
yushi不喜欢

**Comment by yushijinhun** [comment]
啊，怎么变成我的锅了啊
（最近在补作业，没空搞这个项目）

**Comment by CatMe0w** [comment]
唔……MD确实是很棒的设计，比windows的马赛克磁铁有质感，看起来也爽的多，为何不试试呢

**Comment by ghost** [comment]
可以加个自定义 UI 的功能，方便用户切换自己喜欢的主题。
说实话，我也不怎么喜欢棱角分明的磁块。

**Comment by yushijinhun** [comment]
可以通过自定义CSS改变ui外观

**Comment by yushijinhun** [comment]
我开了一个QQ群：485650351

如果各位对开发有什么建议欢迎在此群交流
