### ISSUE TITLE
这个启动器可以开发成java版。

### ISSUE THREAD

**Issue by pongfcnkl** [to2mbn/LoliXL#3]
java的优点就是跨平台，现在MAC和linux只有正版启动器可用了，HMCL不说了。。

**Comment by NekoCaffeine** [comment]
这个项目本身就是用Java进行开发，代码统计你可以看到95.9%都是Java代码，只不过该项目目前已暂停开发

**Comment by yushijinhun** [comment]
本项目已咸鱼。
